config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about', path: :about

  root 'welcome#index' 
  resources :feeds
end

app/models/create_feed.rb
class CreateFeed < ActiveRecord::Base
end

app/models/feed.rb
class Feed < ActiveRecord::Base

  def entries(num = 3)
    Feedjira::Feed.add_common_feed_entry_element("img")
    feed = Feedjira::Feed.fetch_and_parse(url)
    feed.entries.take(num)
    # add_items(feed.entries)  # Saving items to database
  end

  def feed_title
    feed = Feedjira::Feed.fetch_and_parse(url)
    title = feed.title
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def index
    @feeds = Feed.all
    @feed = Feed.new
  end

  def show
    @feed = Feed.find(params[:id])
    @title = @feed.feed_title
    @entries = @feed.entries
  end

  def new 
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)
    if @feed.save
      redirect_to feeds_path
    else
      redirect_to feeds_path
    end
  end

  private

  def feed_params
    params.require(:feed).permit(:name, :url)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper

  def get_info(entry)
    entry.summary || entry.content
  end

end

app/views/feeds/index.html.erb
<h2>Feed Page</h2>

<div class="row">
  <div class="small-8 columns">
    <div class="input-group">
  
      <%= form_for @feed do |f| %>
          <%= f.label :URL, class: "form_label" %>
          <%= f.text_field :url %>
          <%= f.submit "Submit", class: "button postfix" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-10 columns">
  <% @feeds.each do |feed| %>
  <!-- Create a link to go to show page -->
    <% if feed.name == nil %>
    <h3><%= link_to feed.url, feed %>
    <% else %>  
     <h3><%= link_to feed.name, feed %>
    <% end %>
  <!--  -->
    <% feed.entries.each do |entry| %>
      <h4><%= sanitize link_to entry.title %></h4>
      <p><%= sanitize get_info(entry), length: 550 %></p>
    <% end %>
  <% end %>
</div>
</div>

app/views/feeds/show.html.erb
<h2><%= @feed.url %></h2>

<%= @title %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reader</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="small-12 columns">

      <nav class="navigation">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Feed", feeds_path %></li>
      </nav>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/welcome/about.html.erb
About me

app/views/welcome/index.html.erb
<h1>Hello</h1>